// DO NOT EDIT! Auto-generated by github.com/mgutz/razor

package views

import (
	"github.com/mgutz/razor/razor"
)

// Layout is generated
func Layout(title string, body razor.SafeBuffer) razor.SafeBuffer {
	_buffer := razor.NewSafeBuffer()
	_buffer.WriteString("\n\n<html>\n  <head></head>\n  <body>\n    ")
	_buffer.WriteSafe(body)
	_buffer.WriteString("\n  </body>\n</html>")

	return _buffer
}
